// Generated by .codex/skills/wiki-sync/scripts/sync_wiki.py
import { defineConfig } from "vitepress";

const activeItems = [

];

const archivedItems = [
  { text: "use-positive-idf-bm25", link: "/changes/archive/2026-07-11-use-positive-idf-bm25/" },
  { text: "show-retrieval-stage-ranks", link: "/changes/archive/2026-07-11-show-retrieval-stage-ranks/" },
  { text: "remove-project-config-from-git-history", link: "/changes/archive/2026-07-11-remove-project-config-from-git-history/" },
  { text: "remove-compose-runtime-config", link: "/changes/archive/2026-07-11-remove-compose-runtime-config/" },
  { text: "refine-chat-knowledge-aiops-ui", link: "/changes/archive/2026-07-11-refine-chat-knowledge-aiops-ui/" },
  { text: "polish-chat-and-aiops-interactions", link: "/changes/archive/2026-07-11-polish-chat-and-aiops-interactions/" },
  { text: "pace-chat-typewriter-rendering", link: "/changes/archive/2026-07-11-pace-chat-typewriter-rendering/" },
  { text: "move-chat-history-to-workspace-sidebar", link: "/changes/archive/2026-07-11-move-chat-history-to-workspace-sidebar/" },
  { text: "manage-mcp-connections", link: "/changes/archive/2026-07-11-manage-mcp-connections/" },
  { text: "limit-qwen-embedding-batch-size", link: "/changes/archive/2026-07-11-limit-qwen-embedding-batch-size/" },
  { text: "improve-aiops-report-experience", link: "/changes/archive/2026-07-11-improve-aiops-report-experience/" },
  { text: "hide-empty-chat-placeholder", link: "/changes/archive/2026-07-11-hide-empty-chat-placeholder/" },
  { text: "fix-knowledge-document-scrolling", link: "/changes/archive/2026-07-11-fix-knowledge-document-scrolling/" },
  { text: "fix-chat-turn-streaming", link: "/changes/archive/2026-07-11-fix-chat-turn-streaming/" },
  { text: "extract-user-config-and-chat-assets", link: "/changes/archive/2026-07-11-extract-user-config-and-chat-assets/" },
  { text: "expand-java-ecommerce-aiops-fixtures", link: "/changes/archive/2026-07-11-expand-java-ecommerce-aiops-fixtures/" },
  { text: "durable-background-job-runtime", link: "/changes/archive/2026-07-11-durable-background-job-runtime/" },
  { text: "collect-user-feedback", link: "/changes/archive/2026-07-11-collect-user-feedback/" },
  { text: "auto-dismiss-global-feedback", link: "/changes/archive/2026-07-11-auto-dismiss-global-feedback/" },
  { text: "adopt-standard-progressive-skills", link: "/changes/archive/2026-07-11-adopt-standard-progressive-skills/" },
  { text: "add-session-memory-modes", link: "/changes/archive/2026-07-11-add-session-memory-modes/" },
  { text: "add-reranked-knowledge-retrieval", link: "/changes/archive/2026-07-11-add-reranked-knowledge-retrieval/" },
  { text: "add-openspec-wiki", link: "/changes/archive/2026-07-11-add-openspec-wiki/" },
  { text: "add-hybrid-knowledge-retrieval", link: "/changes/archive/2026-07-11-add-hybrid-knowledge-retrieval/" },
  { text: "store-aiops-evidence-and-reports", link: "/changes/archive/2026-07-10-store-aiops-evidence-and-reports/" },
  { text: "run-aiops-diagnosis-tasks", link: "/changes/archive/2026-07-10-run-aiops-diagnosis-tasks/" },
  { text: "refine-knowledge-document-layout", link: "/changes/archive/2026-07-10-refine-knowledge-document-layout/" },
  { text: "refactor-local-project-startup", link: "/changes/archive/2026-07-10-refactor-local-project-startup/" },
  { text: "redesign-chinese-chatgpt-workspace", link: "/changes/archive/2026-07-10-redesign-chinese-chatgpt-workspace/" },
  { text: "persist-diagnosis-cases-to-knowledge-base", link: "/changes/archive/2026-07-10-persist-diagnosis-cases-to-knowledge-base/" },
  { text: "observability-baseline", link: "/changes/archive/2026-07-10-observability-baseline/" },
  { text: "localize-local-development-guides", link: "/changes/archive/2026-07-10-localize-local-development-guides/" },
  { text: "knowledge-answer-citation-view", link: "/changes/archive/2026-07-10-knowledge-answer-citation-view/" },
  { text: "integrate-real-mcp-tools", link: "/changes/archive/2026-07-10-integrate-real-mcp-tools/" },
  { text: "generate-and-upload-cls-logs", link: "/changes/archive/2026-07-10-generate-and-upload-cls-logs/" },
  { text: "fix-knowledge-indexing-experience", link: "/changes/archive/2026-07-10-fix-knowledge-indexing-experience/" },
  { text: "create-readme", link: "/changes/archive/2026-07-10-create-readme/" },
  { text: "create-ecommerce-aiops-fixtures", link: "/changes/archive/2026-07-10-create-ecommerce-aiops-fixtures/" },
  { text: "correct-runtime-readiness-checks", link: "/changes/archive/2026-07-10-correct-runtime-readiness-checks/" },
  { text: "configure-chat-prompt-skills", link: "/changes/archive/2026-07-10-configure-chat-prompt-skills/" },
  { text: "complete-observability-baseline", link: "/changes/archive/2026-07-10-complete-observability-baseline/" },
  { text: "build-vue-app-shell", link: "/changes/archive/2026-07-10-build-vue-app-shell/" },
  { text: "build-knowledge-base-ui", link: "/changes/archive/2026-07-10-build-knowledge-base-ui/" },
  { text: "build-chat-experience", link: "/changes/archive/2026-07-10-build-chat-experience/" },
  { text: "build-aiops-diagnosis-ui", link: "/changes/archive/2026-07-10-build-aiops-diagnosis-ui/" },
  { text: "automate-structured-diagnosis-cases", link: "/changes/archive/2026-07-10-automate-structured-diagnosis-cases/" },
  { text: "audit-agent-tool-calls", link: "/changes/archive/2026-07-10-audit-agent-tool-calls/" },
  { text: "add-readiness-and-config-checks", link: "/changes/archive/2026-07-10-add-readiness-and-config-checks/" },
  { text: "add-document-chunking-strategies", link: "/changes/archive/2026-07-10-add-document-chunking-strategies/" },
  { text: "active-alert-subscription-entry", link: "/changes/archive/2026-07-10-active-alert-subscription-entry/" },
  { text: "stream-rag-chat", link: "/changes/archive/2026-07-09-stream-rag-chat/" },
  { text: "setup-milvus-vector-store", link: "/changes/archive/2026-07-09-setup-milvus-vector-store/" },
  { text: "run-document-indexing-jobs", link: "/changes/archive/2026-07-09-run-document-indexing-jobs/" },
  { text: "provide-knowledge-retrieval-tool", link: "/changes/archive/2026-07-09-provide-knowledge-retrieval-tool/" },
  { text: "manage-knowledge-documents", link: "/changes/archive/2026-07-09-manage-knowledge-documents/" },
  { text: "manage-chat-sessions", link: "/changes/archive/2026-07-09-manage-chat-sessions/" },
  { text: "centralize-project-configuration", link: "/changes/archive/2026-07-09-centralize-project-configuration/" },
  { text: "standardize-docker-compose-startup", link: "/changes/archive/2026-07-08-standardize-docker-compose-startup/" },
  { text: "setup-sqlite-memory-repositories", link: "/changes/archive/2026-07-08-setup-sqlite-memory-repositories/" },
  { text: "ignore-idea-files", link: "/changes/archive/2026-07-08-ignore-idea-files/" },
  { text: "define-api-and-sse-contracts", link: "/changes/archive/2026-07-08-define-api-and-sse-contracts/" },
  { text: "configure-qwen-openai-provider", link: "/changes/archive/2026-07-08-configure-qwen-openai-provider/" },
  { text: "bootstrap-project-foundation", link: "/changes/archive/2026-07-08-bootstrap-project-foundation/" },
  { text: "add-user-authentication", link: "/changes/archive/2026-07-08-add-user-authentication/" },
  { text: "add-authorization-and-tenant-isolation", link: "/changes/archive/2026-07-08-add-authorization-and-tenant-isolation/" },
];

export default defineConfig({
  lang: "zh-CN",
  title: "Super AI WIKI",
  description: "Super AI 项目文档与 OpenSpec 变更记录",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "首页", link: "/" },
      { text: "变更 WIKI", link: "/changes/" }
    ],
    sidebar: {
      "/changes/": [
        { text: "总览", items: [{ text: "变更索引", link: "/changes/" }] },
        { text: "进行中", collapsed: false, items: activeItems },
        { text: "已归档", collapsed: true, items: archivedItems }
      ]
    },
    search: { provider: "local" },
    outline: { level: [2, 3], label: "本页目录" },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部"
  }
});
